[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
reputesol_program = "3jSgCkDsvWqaffHHy3wKJ6jYqXo2zxhVbg81gUbMhwgL"

[programs.devnet]
reputesol_program = "3jSgCkDsvWqaffHHy3wKJ6jYqXo2zxhVbg81gUbMhwgL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 5000

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"
